# Generated by Django 5.1.7 on 2025-03-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANDY', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('donate', 'Донат'), ('ecology', 'Екологія'), ('military', 'Військове'), ('help', 'Допомога'), ('medicine', 'Медицина'), ('community', 'Громадська діяльність'), ('social', 'Соціальні ініціативи'), ('emergency', 'Надзвичайні ситуації'), ('mental-health', 'Психологічна підтримка'), ('reconstruction', 'Відновлення інфраструктури')], max_length=20),
        ),
    ]
